Improve error handling in RPC test scripts

diff --git a/rpc-test/get_address b/rpc-test/get_address
--- a/rpc-test/get_address
+++ b/rpc-test/get_address
@@ -2,22 +2,19 @@
 dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 source ${dir}/_common
 
-# Call without private data
-request='{"private":false}'
-
-data=$(send_request get_address ${request})
-
-print_request_data ${request}
-echo ""
-print_response_data ${data}
-
-echo ""
-
 # Call with private data
 request='{"private":true}'
 
 data=$(send_request get_address ${request})
+ret=$?
 
 print_request_data ${request}
+
+if [ "${ret}" == 1 ]; then 
+    echo ""
+    echo "Request failed."
+    exit 1
+fi
+
 echo ""
 print_response_data ${data}
diff --git a/rpc-test/get_message b/rpc-test/get_message
--- a/rpc-test/get_message
+++ b/rpc-test/get_message
@@ -6,8 +6,16 @@ key=$1
 request='{"key":"'${key}'"}'
 
 data=$(send_request get_message ${request})
+ret=$?
 
 print_request_data ${request}
+
+if [ "${ret}" == 1 ]; then 
+    echo ""
+    echo "Request failed."
+    exit 1
+fi
+
 echo ""
 print_response_data ${data}
 
diff --git a/rpc-test/get_message_details b/rpc-test/get_message_details
--- a/rpc-test/get_message_details
+++ b/rpc-test/get_message_details
@@ -3,7 +3,15 @@ dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 source ${dir}/_common
 
 data=$(send_request_no_param get_message_details)
+ret=$?
 
 print_request_data_no_param
+
+if [ "${ret}" == 1 ]; then 
+    echo ""
+    echo "Request failed."
+    exit 1
+fi
+
 echo ""
 print_response_data ${data}
diff --git a/rpc-test/send_message b/rpc-test/send_message
--- a/rpc-test/send_message
+++ b/rpc-test/send_message
@@ -8,7 +8,15 @@ message=$(echo "$2" | tr -d '"' | base64)
 request='{"address":"'${address}'","message":"'${message}'"}'
 
 data=$(send_request send_message ${request})
+ret=$?
 
 print_request_data ${request}
+
+if [ "${ret}" == 1 ]; then 
+    echo ""
+    echo "Request failed."
+    exit 1
+fi
+
 echo ""
 print_response_data ${data}
